### ISSUE TITLE
Performance: iPhone: Lesson 1: first-time page load is slow, resulting in activity "ghosts" 

### ISSUE THREAD

**Issue by mpmikesell** [MusicAsLanguage/mobileapp#110]
![image](https://user-images.githubusercontent.com/63743659/152277799-1afe7a24-dda4-4c27-84fd-ceb352ef6d9f.png)

**Comment by linsungc** [comment]
Tackling this from both server and client sides.

Server side
1. Set up CDN for better performance and reliability when serving the media.
2. Turn on diagnostics log to be used for troubleshooting potential server side issues

Client side
3. Give user an ability to retry (in progress)
4. Implement local cache (in progress)

If 1st & 2nd address the major issues we saw, we can then work on 3rd & 4th as next set of priorities.

**Comment by linsungc** [comment]
Update as of 2/21.

Server side
1.  Set up CDN for better performance and reliability when serving the media (Done)
2. Turn on diagnostics log to be used for troubleshooting potential server side issues (Done)

Client side
3. Give user an ability to retry (Done)
4. Implement local cache (in progress)

There have been additional loggings and error handling added as part of 3rd item.

Assuming all three changes made so far would address/mitigate the original issue, we will track 4th item above as separate issue in lower priority.

**Comment by linsungc** [comment]
As of now, as mentioned above, all three things are done, and a separate issue for 4th item about cache has been created. Since the majority of the intended work is done, closing this issue. Any new problem around this, should be tracked as new issue.
