### ISSUE TITLE
App icon: replace the current tile image with the new one

### ISSUE THREAD

**Issue by mpmikesell** [MusicAsLanguage/mobileapp#165]
![image](https://user-images.githubusercontent.com/63743659/176570691-0ee4750c-49fd-42d6-abb5-b31c76a9a66f.png)

**Comment by shengyfu** [comment]
@ShuoZhang-dev, @birgithi, Use this attached image with 512x512 resolution:
![appIcon](https://user-images.githubusercontent.com/23369389/176572648-ab19c63b-5d0c-4881-beb3-1cf9909f40c5.png)
.
