### ISSUE TITLE
Account/privacy: Create a way for users to delete their account + data

### ISSUE THREAD

**Issue by mpmikesell** [MusicAsLanguage/mobileapp#167]
MIGHT be needed to publish the app publicly, for Android at least.

**Comment by shengyfu** [comment]
I have merged and deployed the backend change, @birgithi , could you work on the UX to have a Delete User and their Data button in the settings page?

**Comment by linsungc** [comment]
Assigning this issue to myself.

**Comment by linsungc** [comment]
Created PR to add Delete User button under Settings
![MAL-DeleteUser](https://user-images.githubusercontent.com/76028304/183824547-dab0e0e0-aee8-4687-a035-eaee0ecaef72.png)
:

**Comment by linsungc** [comment]
Created PR for review

**Comment by linsungc** [comment]
Merged the change to main.
