### ISSUE TITLE
First song in "Instruction" section has several seconds of silence

### ISSUE THREAD

**Issue by ShuoZhang-dev** [MusicAsLanguage/mobileapp#174]
The song under "Instruction" section "Instructions for Care Givers" has several seconds of silence at the beginning. We need to first make sure this is the problem of the .mp3 file itself, or because of the delay of API.

**Comment by ShuoZhang-dev** [comment]
@shengyfu , would you mind check the mp3 file hosted in the webservice to see whether the mp3 has seconds of silence itself? If yes, we'll need to find someone to chop it.

**Comment by shengyfu** [comment]
I have fixed the introductions.mp3 by trimming the first 9-second: https://malstorecdn.azureedge.net/assets/songs/Instructions.mp3
